[book]
authors = ["The Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Programming Multiple Robots with ROS 2"

[build]
create-missing = false

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/osrf/ros2multirobotbook"
additional-css = ["open-in.css"]

[output.html.fold]
enable = true
